### ISSUE TITLE
Deployment on Arbitrum Rinkeby

### ISSUE THREAD

**Issue by jaybuidl** [kleros/gtcr-injected-uis#6]
Dependencies: 
- https://github.com/kleros/tcr/issues/62
- [Arbitrator contracts](https://github.com/kleros/kleros-v2/blob/master/contracts/README.md#arbitrum-rinkeby-classic---deprecated)

**Comment by greenlucid** [comment]
We could skip this, it would only result on the item not being linked to curate frontend.

**Comment by jaybuidl** [comment]
Deployed -> [/ipfs/QmcMG2rJ2GcY4E2DUHm5EaKn6SPyT1NPAsZB4tiaB4QL2K/index.html](https://ipfs.kleros.io/ipfs/QmcMG2rJ2GcY4E2DUHm5EaKn6SPyT1NPAsZB4tiaB4QL2K/index.html)
